version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "${DOCKER_WEBSERVER_PORT}:80"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
    networks:
      - stream-app-network
    container_name: stream-app
    restart: always
      
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DOCKER_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3906:3306
    volumes:
      - ./stream-docker-compose/volumes/mysql:/var/lib/mysql
    networks:
      - stream-app-network
    container_name: stream-app-database
    restart: always
networks:
  stream-app-network:
    driver: bridge

